apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tailscale

resources:
- ../../base
- sealedsecret.yaml

helmCharts:
- name: tailscale-operator
  repo: https://pkgs.tailscale.com/helmcharts
  version: 1.94.2
  releaseName: tailscale
  namespace: tailscale
  valuesFile: values.yaml
